### ISSUE TITLE
Trader config save

### ISSUE THREAD

**Issue by Droidem** [rvost/DayzServerTools#2]
I am unable to save a trader config document. 

I'm running v0.6.0 and the save button or save as does not update any file due to validation errors. The errors are to be expected as I have a "header" between certain files.  

Example: MMG Pouches doesn't exist but I want it there to separate my items. 
`mmg_boonie_ucp,		                    	*,		5000,		500
			mmg_boonie_multicam_tropic,		                   *,		5000,		500	

			MMG Pouches,*,-1,-1
			MMG_Mag_Pouch_Black,  *, 2500,  500
			MMG_Mag_Pouch_olive,  *, 2500,  500`

Are you willing/able to add a 'ignore validations errors' to save the file?

**Comment by rvost** [comment]
Sorry for the late reply, I left DayzServerTools for a while. The validation rules are currently bit too strict because they are based on the preferences of mine and friends. Thanks for sharing your experience!

I will release a fix soon to make saving more flexible and allow errors to be ignored. I'm going to make validation  configurable  in the future but there is architectural challenge I need to solve first. I'm still thinking about it, so no ETA yet.

**Comment by rvost** [comment]
@Droidem, I just published a [fix](https://github.com/rvost/DayzServerTools/releases/tag/0.6.2). 

Theoretically, you don't need to download anything manually. The application checks for updates on startup and downloads them, and the next time you launch there will be a new version. But I found problem in my release automation. For some reason it doesn't generate delta packages so there *might be* issues with updates. Please let me know if this is the case!

I consider this issue closed. Feel free to open a new one if you run into problems. Thanks again for your feedback!
